studypal/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'studypals'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('studypals.urls')),
]

studypals/urls.py
"""Defines URL patterns for users"""
from django.urls import path, include

from . import views

app_name = 'studypals'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Home page
    path('', views.index, name='index'),
    # Chat page
    path('chat/', views.chat, name='chat'),
    path('dashboard', views.dashboard, name='dashboard'),
    ]

users/urls.py
"""Defines URL patterns for users"""
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Sign up page.
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    ]

studypals/models.py
from django.db import models


# Create your models here.
class ChatBox(models.Model):
    title = models.CharField(max_length=100)
    # owner = models.ForeignKey(User)
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Text(models.Model):
    # chatbox = models.ForeignKey(ChatBox, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text
    
class Course(models.Model):
    code = models.CharField(max_length=10)
    title = models.CharField(max_length=64)
    unit = models.PositiveIntegerField()
    outline = models.TextField()

    def __str__(self):
        return self.code

class TimeTable(models.Model):
    mon = models.TextField()
    tue = models.TextField()
    wed = models.TextField()
    thu = models.TextField()
    fri = models.TextField()

users/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils.choices import DEPT_CHOICES, LEVEL_CHOICES


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    matric_no = models.CharField(max_length=32)
    department = models.CharField(max_length=50, blank=True, null=True, choices=DEPT_CHOICES)
    school_year = models.CharField(max_length=50, blank=True, null=True, choices=LEVEL_CHOICES)

studypals/forms.py
from django import forms

from .models import Text, TimeTable


class TextForm(forms.ModelForm):
    class Meta:
        model = Text
        fields = ['text']
        labels = {'text': ''}
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter a message'})
            }
        
class TimeTableForm(forms.ModelForm):
    class Meta:
        model = TimeTable
        fields = ['mon', 'tue', 'wed', 'thu', 'fri']
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter a message'})
            }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .utils.choices import DEPT_CHOICES, LEVEL_CHOICES

        
class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=50)
    first_name = forms.CharField(max_length=32)
    matric_no = forms.CharField(max_length=32)
    department = forms.ChoiceField(choices=DEPT_CHOICES)
    school_year = forms.ChoiceField(choices=LEVEL_CHOICES)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'matric_no', 'department', 'school_year', 'password1', 'password2']
        labels = {'username': '', 'first_name' : '', 'password1': '', 'password2': '', 'matric_no': '', 'department': '', 'school_year': ''}
        widgets  = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'deparment': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Department'}),
            'school_year': forms.Select(attrs={'class': 'form-select', 'placeholder': 'School Year'}),
            'matric_no': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Matric Number'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}),
            }

studypals/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .utils.web_scraper import main
from .utils.gpt import gpt_response


@login_required
def index(request):
    """The home page for Study Pal."""
    return render(request, 'studypals/index.html')

@login_required
def dashboard(request):
    """The home page for Study Pal."""
    return render(request, 'studypals/dashboard.html')

@login_required
def chat(request):
    """Chat page"""
    response = None
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        query = data.get('message', '')
        # response = main(query)
        print(query)

        chat_response = gpt_response(query)
        print(chat_response)
        return JsonResponse({'response': chat_response})

        
    context = {}
    return render(request, 'studypals/chat.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login
from .forms import SignUpForm

from .models import Account

# Create your views here.
def signup(request):
    """Register a new user."""
    if request.method != 'POST':
        form = SignUpForm()
    else:
        form = SignUpForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # username = form.cleaned_data['username']
            # password = form.cleaned_data['password1']
            # user = authenticate(username=username, password=password)
            # if user is not None:
            login(request, new_user)
            return redirect('studypals:dashboard')  # Redirect to a success page

    context = {'form': form}
    return render(request, 'registration/signup.html', context)

def login_view(request):
    """Log users in."""
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('studypals:chat')  # Redirect to a success page
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'login.html', context)

studypals/templates/studypals/base.html
<!-- {% load static %} -->

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <!-- Google Fonts Link For Icons -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

  <!-- Bootstrap Icon Pack -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

  <!-- <link rel="stylesheet" type="text/css" href="{% static 'studypals/css/chat.css' %}"> -->
  <style>
    /* Import Google font - Poppins */
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap');

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: "Poppins", sans-serif;
    }


    /* body styling */
    body {
      background-color: #222327;
    }

    /* Sidebar styling */
    .sidebar{
      position: fixed; 
      border: 0px solid ;
      outline: 0px solid;
      width: 20%;
      display: inline-block;
      height: 99vh;
      background-color: #000;
      /* box-shadow: 3px 6px 10px black, 3px 6px 10px black  ; */
      border-radius: 0px;
      cursor: pointer;
    }
    .show-sidebar{
      display: none;
      background-color: unset;
      color: white;
      outline: none;
      border: none;
    }
    .hide-sidebar{
      display: none;
      color: white;
      outline: none;
      border: none;
      position: absolute;
      top: 10px;
      right: -40px;
      background-color: #343541;
    }

    @media (max-width : 902px ) {
      .show-sidebar, .hide-sidebar{
        display: block;
      }
      .sidebar{
        width: 90%;
        max-width: 300px;
        z-index: 100;
        left: -100%;
      }
      .sidebar.show{
        left: 0;
      }
      .chat-block{
        width: 100% !important;
        left: 0 !important;
        height: 100vh;
      }
    }

    .sidebar .Logout{
      border: none;
      padding: 10px 10px;
      margin-top: 30%;
      text-align: center;
    }
    .sidebar .Logout:active{
      background-color: #2A2B32;
    }
    .sidebar #Logout-btn{
        display: inline-block;
        color: #fff;
        vertical-align: bottom;
        padding-right: 10px;
        
    }
    .Logout p{
      display: inline;
      font-size: 0.8em;
    }
    .Logout a{
      color: #fff;
      text-decoration: none;
    }
    .sidebar .history{
      border: none;
      padding: 10px 10px;
      margin-top: 30%;
      text-align: center;
    }
    .sidebar .history:active{
      background-color: #2A2B32;
    }
    .sidebar #history-btn{
        display: inline-block;
        color: #fff;
        vertical-align: bottom;
        padding-right: 10px;
    }
    .history p{
      display: inline;
      color: rgba(255, 255, 255, 1);
      font-size: 0.8em;
    }


    .sidebar .chat{
      border: 1px solid #CACCCE;
      border-radius: 24px;
      background-color: #131314;
      width: 70%;
      padding: 5px 5px;
      text-align: center;
      justify-content: center;
    }

    .sidebar #chat-btn{
        display: inline-block;
        color: #CACCCE;
        vertical-align: bottom;
        padding-right: 10px;
        
    }
    .chat p{
      display: inline;
      color: #CACCCE;
      font-size: 0.8em;
    }

    .sidebar hr{
      border: 1px solid #555659;
      width: 100%;
      margin-top: 12em;
    
    }


    /* Chats area styling */
    .chat-block{
      width: 70%;
      border:1px solid red;
      position: relative;
      left: 25%;
      height: 100vh;
      padding-top: -2%;
      border-radius: 20px;
      
    }
    /* Chats container styling */
    .chat-container {
      overflow-y: auto;
      max-height: 100vh;
      padding-bottom: 150px;
      border: none;
    }

    :where(.chat-container, textarea)::-webkit-scrollbar {
      width: 6px;
    }
    :where(.chat-container, textarea)::-webkit-scrollbar-track {
      background: var(--incoming-chat-bg);
      border-radius: 25px;
    }
    :where(.chat-container, textarea)::-webkit-scrollbar-thumb {
      background: var(--icon-color);
      border-radius: 25px;
    }

    .user-container .chatbot-container{
      border: 1px solid #202123;
      padding: 25px 25px;
      justify-content: center;
    }
    .chat-container img{
      width: 40px;
      height: 35px;
      border-radius: 2px;
      display: inline-block;
      vertical-align: bottom;
    }
    .chatbot-container{
      border: 1px solid #40414F;
      border-radius: 24px;
      justify-content: center;
      color: white;
      background-color: #131314;
    }
    .chat-container p{
      font-size: 0.8rem;
      padding: 0 50px 0 25px;
      color:#fff;
      display: inline;
    }

    /* Typing container styling */
    .typing-container {
      position: fixed;
      bottom: 0;
      width: inherit;
      display: flex;
      padding: 20px 10px;
      justify-content: center;
      border-top: 1px solid ;
      border: none;
    }
    .typing-container .typing-content {
      display: flex;
      max-width: 950px;
      width: 100%;
      align-items: flex-end;
    
    }
    .typing-container .typing-textarea {
      width:100%;
      display: flex;
      position: relative;
    
    }
    .typing-textarea input {
      resize: none;
      height: 55px;
      width: 100%;
      border: none;
      padding: 15px 45px 15px 20px;
      font-size: 0.9rem;
      border-radius: 24px;
      max-height: 250px;
      background: #131314;
      outline: 1px solid ;
      color: #CACCCE;
    }
    .a-text {
      color: #CACCCE;
    }
    .typing-textarea input::placeholder {
      color: #CACCCE;
    }
    .typing-content span {
      width: 55px;
      height: 55px;
      display: flex;
      border-radius: 4px;
      font-size: 1.35rem;
      align-items: center;
      justify-content: center;
      color: white;
    }
    .typing-textarea span {
      position: absolute;
      right: 0;
      bottom: 0;
      visibility: hidden;
    }
    .typing-textarea input:valid ~ span {
      visibility: visible;
    }
  </style>

<script>
  const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
</script>

  
  <title>Study Pal</title>

</head>
<body>

  <nav class="navbar navbar-expand-md bg-body-tertiary" style="background-color: #000;">

    <a class="navbar-brand a-text" href="{% url 'studypals:index' %}">Study Pal</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
   
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
              <span class="navbar-text" style="color:white">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link a-text" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link a-text" href="{% url 'users:signup' %}">Sign up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link a-text" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>
  
  <div>
    <div class="">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </div>
  <script>
    const SHOW_SIDEBAR_BTN = document.querySelector('.show-sidebar')
    const HIDE_SIDEBAR_BTN = document.querySelector('.hide-sidebar')
    const SIDEBAR = document.querySelector('.sidebar')
    const SEND_BTN = document.querySelector('.typing-textarea #send-btn')
    const INPUT_AREA = document.querySelector('#chat-input')
    const CHAT_CONTAINER = document.querySelector('.chat-container')

    SHOW_SIDEBAR_BTN.addEventListener('click', () => {
        SIDEBAR.classList.add('show')
        SIDEBAR.classList.remove('hide')
    })

    HIDE_SIDEBAR_BTN.addEventListener('click', () => {
        SIDEBAR.classList.remove('show')
        SIDEBAR.classList.add('hide')
    })

    // const sendMessage = () => {
    //     if(INPUT_AREA.value != '' && INPUT_AREA.value != ' '){
    //         const messageEl = document.createElement('div')
    //         messageEl.innerHTML = `<div class="user-container">
    //         <img src="../images/user.png" alt=""><p>${INPUT_AREA.value}</p>
    //     </div> 
    //     <div class="chatbot-container">
    //       <i class="bi bi-robot"></i><p>No response to display</p>
    //     </div>`
    //         CHAT_CONTAINER.appendChild(messageEl)
    //         INPUT_AREA.value = ''
    //         CHAT_CONTAINER.scrollTop += CHAT_CONTAINER.clientHeight
    //     }
    // }
    // Get the CSRF token from the cookie
    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
      }
      return cookieValue;
    }

    const sendMessage = () => {
      const userMessage = INPUT_AREA.value.trim(); // Remove leading and trailing whitespace

      if (userMessage !== '') {
          const messageEl = document.createElement('div');
          
          // Display user message
          messageEl.innerHTML = `<div class="user-container">
              <img src="../images/user.png" alt=""><p>${userMessage}</p>
          </div>`;
          
          CHAT_CONTAINER.appendChild(messageEl);
          INPUT_AREA.value = '';
          CHAT_CONTAINER.scrollTop += CHAT_CONTAINER.clientHeight;

          // Get the CSRF token
          const csrftoken = getCookie('csrftoken');

          // Send user message to the backend
          fetch('/chat/', {
              method: 'POST',
              headers: {
                  'Content-Type': 'application/json',
                  'X-CSRFToken': csrftoken // Include the CSRF token in the request headers
                },
              body: JSON.stringify({ message: userMessage })
            })
          .then(response => response.json())// Response will be HTML content
          .then(data => {
              const botMessageEl = document.createElement('div');
              
              // Display chatbot response
              botMessageEl.innerHTML = `<div class="chatbot-container">
                  <i class="bi bi-robot"></i><p>${data.response}</p>
              </div>`;
              
              CHAT_CONTAINER.appendChild(botMessageEl);
              CHAT_CONTAINER.scrollTop += CHAT_CONTAINER.clientHeight;
            })
          .catch(error => {
              console.error('Error fetching chatbot response:', error);
          });
        }
    };


    INPUT_AREA.addEventListener('keypress', (e) => {
        // console.log(e.target.value, 'oya')
        if(e.key == 'Enter'){
        console.log(e.target.value, 'oya')
            INPUT_AREA.value = ''
        }
    })
    INPUT_AREA.addEventListener('keydown', (e) => {
        if(e.key == 'Enter'){
            sendMessage()
        }
    })
    SEND_BTN.addEventListener('click', sendMessage)
  </script>
</body>

</html>

studypals/templates/studypals/chat.html
<!DOCTYPE html>
<!-- {% load static %} -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'studypals/css/chat.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@700&family=Coiny&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Salsa&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <title>DASHBOARD</title>
    <script>
      const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    </script>
</head>
<body>
 <!-- side bar -->
 <div class="sidebar">
  <button class="hide-sidebar">
    <span id="close-btn" class="material-symbols-rounded">close</span>
  </button>
  <div class="chatbot"></div>
  <ul class="list">
    <div class="Add"><span id="Add-btn" class="material-symbols-rounded" class="Add-span">Add</span><p>New Chat</p></div>
    <div class="history"><span id="history-btn" class="material-symbols-rounded" class="history-span">history</span><p>Assist with user History.</p></div>
      <div class="Logout"><span id="Logout-btn" class="material-symbols-rounded" class="Logout-span">Logout</span><p><a href="{% url 'users:logout' %}">Log Out.</a></p></div>
      <hr>
  </ul>
</div>
<!-- Chats container -->
<div class="bot">
  <button class="show-sidebar">
    <span id="menu-btn" class="material-symbols-rounded">menu</span>
  </button>
<div class="chat-container"></div>

<!-- Typing container -->
<div class="typing-container">
      <div class="typing-content">
    <div class="typing-textarea">
      <input id="chat-input" spellcheck="" placeholder="Type In Your Message" required />
        <span id="send-btn" style="cursor: pointer;" class="material-symbols-rounded">send</span>
    </div>
</div>
</div>
</div>

<script src="{% static 'studypals/js/chat.js' %}"></script>
</body>
</html>

studypals/templates/studypals/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Welcome to StudyPal</title>
    <!-- <link rel="shortcut icon" href="{% static studypals/images/study.svg" type="image/x-icon" /> -->
    <link rel="stylesheet" href="{% static 'studypals/css/style.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200;0,6..12,300;0,6..12,400;0,6..12,500;1,6..12,200&display=swap" 
      rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500&display=swap" rel="stylesheet">
    <script src="{% static 'studypals/js/script.js' %}" defer></script>
  <body>    
    <!-- navigationbar -->

    <div class="nav__content">
      <div class="nav__bar">
        <div class="nav__links">
          <a href="{% url 'users:login' %}" class="nav__link">Login</a>
          <a href="{% url 'users:signup' %}" class="nav__link">Get Started</a>
        </div>
        <div class="nav__logo">
          <img src="{% static 'studypals/images/img/study.svg' %}" alt="StudyPal" id="icon">
          <span id="logo__text">StudyPAL</span>
        </div>
        </div>
      </div>
<!-- navigationbar end -->
    <section class="main main--animation">
      <div class="main__box">
        <div class="main__about">
          <div class="content">
            <h3>Welcome to <span class="highlight">StudyPAL</span></h3>
            <article class="main__paragraph">
              Introducing your very own intelligent virtual assistant designed exclusively for educational purposes, ready to lend a hand at every stage of the learning journey!
            </article>
          </div>
          <div class="content" >
            <h3>Talk with <span class="highlight">AI</span></h3>
            <article class="main__paragraph">
              StudyPAL! Our brilliant AI assistant is at your service, ready to promptly and precisely address any concerns you may have regarding courses, syllabi, timetables or other pertinent details. We are dedicated to ensuring that our users excel in their academic pursuits and we remain steadfastly available for assistance whenever needed.
            </article>
          </div>
          <div class="content">
            <h3>Get good <span class="highlight">Grades</span></h3>
            <article class="main__paragraph">
              Embrace the ultimate solution to enhance your education with our intelligent virtual assistant, dedicated to guiding you through every stage of your learning journey. Allow us to be by your side as a reliable companion and watch how we transform the way you approach academic challenges!
            </article>
          </div>
        </div>
        <div class="main__illustration">
        <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" id="blob__1">
          <path fill="#F2EE9D" d="M35.7,-38.1C46.9,-33.1,57.3,-22.5,64.7,-7.4C72.2,7.7,76.8,27.4,68.6,37.8C60.4,48.2,39.4,49.4,20.9,55C2.4,60.7,-13.5,70.8,-23,66.1C-32.4,61.3,-35.4,41.8,-43,26.1C-50.6,10.4,-62.9,-1.4,-66.2,-16.8C-69.6,-32.1,-64.1,-51,-51.6,-55.8C-39.1,-60.6,-19.5,-51.3,-3.7,-47C12.2,-42.6,24.4,-43.1,35.7,-38.1Z" transform="translate(100 100)" />
        </svg>
        <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" id="blob__2">
          <path fill="#7A9D54" d="M35.7,-38.1C46.9,-33.1,57.3,-22.5,64.7,-7.4C72.2,7.7,76.8,27.4,68.6,37.8C60.4,48.2,39.4,49.4,20.9,55C2.4,60.7,-13.5,70.8,-23,66.1C-32.4,61.3,-35.4,41.8,-43,26.1C-50.6,10.4,-62.9,-1.4,-66.2,-16.8C-69.6,-32.1,-64.1,-51,-51.6,-55.8C-39.1,-60.6,-19.5,-51.3,-3.7,-47C12.2,-42.6,24.4,-43.1,35.7,-38.1Z" transform="translate(100 100)" />
        </svg>
        <div class="content__ill">
          <img src="{% static 'studypals/images/img/ill-1.svg" alt="illustration" class="image__ill image__ill--trans">
        </div>
      </div>
    </section>
  </body>
</html>